# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
 # Azure service connection established during pipeline creation
  azureSubscription: 196840ce-5989-4cce-99c6-a7933469624e
  appName: pipelines_dotnet_core
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureWebApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: azureServiceCreation
    appType: webAppLinux
    appName: $(appName)
    resourceGroupName: pipeline
    package: $(System.ArtifactsDirectory)/**/*.zip
