# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
 # Azure service connection established during pipeline creation
  azureSubscription: 196840ce-5989-4cce-99c6-a7933469624e
  appName: pipelines_dotnet_core
  buildConfiguration: 'Release'

steps:


- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '5.0.x'
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions
    packageType: runtime
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    nugetConfigPath: NuGet.config    # Relative to root of the repository
    feedsToUse: 'select'
    vstsFeed: 'my-vsts-feed' # A series of numbers and letters

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1 # Add this at the end of your file
  inputs:
    azureSubscription: azureServiceCreation
    appType: webAppLinux
    appName: $(appName)
    resourceGroupName: pipeline
    package: $(System.ArtifactsDirectory)/**/*.zip

